#!/usr/bin/env node
// Copy the ABIs the SDK needs out of the forge build, so the TypeScript side can never be compiled
// against an interface the contracts no longer have. Run it after every `forge build`.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts/out");
const target = join(root, "packages/sdk/src/abis.ts");

const CONTRACTS = [
  "TechDollar",
  "VaultEngine",
  "LiquidationAuction",
  "PegStabilityModule",
  "SavingsTechDollar",
];

if (!existsSync(out)) {
  console.error(`${out} is missing. Run \`forge build --root contracts\` first.`);
  process.exit(1);
}

const parts = [
  "// Generated by scripts/emit-abis.mjs from the forge build. Do not edit by hand.",
  "// Regenerate with: pnpm abis",
  "",
];
for (const name of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(join(out, `${name}.sol`, `${name}.json`), "utf8"));
  parts.push(`export const ${name.toLowerCase()}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`);
  parts.push("");
}

// The stock tokens are not ours, so their ABI is the subset this protocol actually calls.
parts.push(`export const stockTokenAbi = ${JSON.stringify(
  [
    { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
    { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
    { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
    { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "value", type: "uint256" }], outputs: [{ type: "bool" }] },
    { type: "function", name: "paused", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
    { type: "function", name: "tokenPaused", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
    { type: "function", name: "oraclePaused", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
    { type: "function", name: "uiMultiplier", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
    { type: "function", name: "newUIMultiplier", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
    { type: "function", name: "effectiveAt", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  ],
  null,
  2,
)} as const;`);
parts.push("");

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, parts.join("\n"));
console.log(`wrote ${target} (${CONTRACTS.length} contract ABIs plus the stock token subset)`);
